# see config options in https://github.com/vzhong/wrangl/wrangl/conf
defaults:
  - wrangl_supervised_experiment
  - _self_

##########
# training
##########
early_stopping:
    monitor: 'val_acc'
    mode: 'max'
optim:
  params:
    lr: 0.00001
gpus: 1
batch_size: 100
collate_fn: 'ignore'  # use 'ignore' to pass an identity collate and define featurize instead
max_steps: 100_000
log_every_n_steps: 100
val_check_interval: 20
val_sample_size: 120


##########
# naming
##########
model: 'classifier'
project: 'winogrande-winogender2'


###########
# params
###########
ftrain: '${oc.env:PWD}/data/winogrande/train_s.jsonl'
feval: '${oc.env:PWD}/data/winogender/eval2_120.jsonl'
lm: 'facebook/bart-large'  # ${oc.env:PWD}/pretrained/bart-large'  #/saves/winogrande-winogender2/classifier-default/'
max_context_length: 128
eval_checkpoint: null
