# see config options in https://github.com/vzhong/wrangl/wrangl/conf
defaults:
  - wrangl_supervised_experiment
  - _self_

##########
# training
##########
early_stopping:
    monitor: 'val_acc'
    mode: 'max'
optim:
  params:
    lr: 0.00001
gpus: 1
batch_size: 100
collate_fn: 'ignore'  # use 'ignore' to pass an identity collate and define featurize instead
max_steps: 100_000
log_every_n_steps: 100
val_check_interval: 100
val_sample_size: 100


##########
# naming
##########
model: 'classifier'
project: 'wrangl-winogrande'


###########
# params
###########
ftrain: '${oc.env:PWD}/data/winogrande/train_xl.jsonl'
feval: '${oc.env:PWD}/data/winogrande/dev.jsonl'
lm: '${oc.env:PWD}/pretrained/bart-large'
max_context_length: 128
